### ISSUE TITLE
Code Analysis

### ISSUE THREAD

**Issue by mripv6** [Sloopdog/Arduino-code-for-use-with-Nest-and-Dometic-Ac#1]
Thanks for this work Sloopdog! I'm having trouble with my thermostat. It's very sensitive to RF (ham radio) and I want to replace the thermostat with an analog version. (not a NEST).

Have you figured out what type of communication protocol is in use? It's interesting to me that the first set of pulses use a 500uS slot and then another set of pulses use 5 uS. I wrote a small program to create a visual pulse train so I can see how the code changes, but I'm not sure what I'm looking at. Next time I bring my trailer home, it will be interesting to see if I get something similar using my logic analyzer.

Hope this message gets to you! Thanks again for your work.

**Comment by Sloopdog** [comment]
I have not figured out what protocol it uses. I think it may be something simple but I just didn't dig into it too much. And are you having problems with the stock setup because of the ham radio? And that's why you want to replace it. If that is the case then this solution may have the same problem as before because your still sending the same signal. But you could use any kind of thermostat with this setup because it was made to work with any household thermostat. Amd let me know if you find something different. Let me know if you need any more help with this

**Comment by mripv6** [comment]
Thanks for your reply. You have a good point. It could be RFI.

I need to put an oscilloscope on the signal line to see if it's an RFI
problem or a problem with the capacitive switches. The capacitive
switches are notorious for being susceptible to RFI, which is why I
started there. I may be able to remove the control board and wire up an
analog thermostat, too. Time for some surgery!

**Comment by sooonmitch** [comment]
@mripv6 How did this go? Able to close the issue?

**Comment by mripv6** [comment]
Yes, close the issue. I'm going to give this another attempt. Since I can't keep my trailer at my house because of HOA rules, I keep running out of time. I have a picoscope with the same kind of logic analyzer that you have. Thanks for all your work on this! BTW, there are 12 to 24 volt converters so you don't have to depend on the AC adapter. You probably know that already!
